export default {
  POP_COORDONNEES: {
    lat: 48.859903,
    lon: 2.340929
  },
  PRODUCTEUR: "MUSEE",
  BASE: "Collections des musées de France (Joconde)",
  CONTIENT_IMAGE: "oui",
  POP_CONTIENT_GEOLOCALISATION: "oui",
  POP_IMPORT: [],
  REFMIS: "",
  ADPT: [],
  APPL: "",
  APTN: "Van Ouwenhuysen Constant",
  ATTR: "",
  AUTR: "DIAZ DE LA PENA Narcisse",
  BIBL:
    "Catalogue sommaire illustré des peintures du musée du Louvre et du musée d'Orsay, Ecole française, III, Paris, 1986, p. 224",
  COMM: "",
  CONTACT: "photo@rmn.fr",
  COOR: "",
  COPY: "© Musée du Louvre, © Direction des Musées de France, 1999",
  DACQ: "1889",
  DATA: "",
  DATION: "",
  DDPT: "",
  DECV: "",
  DENO: ["tableau"],
  DEPO: "",
  DESC: "",
  DESY: "1987 AVANT",
  DIFFU: "non",
  DIMS: "H. 61, l. 50",
  DMAJ: "1999-05-14",
  DMIS: "",
  DOMN: ["peinture"],
  DREP: "",
  ECOL: ["France"],
  EPOQ: [],
  ETAT: [],
  EXPO: "",
  GENE: [],
  GEOHI: [],
  HIST: "",
  IMAGE: "oui",
  IMG: ["joconde/000PE001028/96de11977.jpg"],
  INSC: ["daté", "signé"],
  INV: "RF 542",
  LABEL: "Musée de France#au sens de la loi n°2002-5 du 4 janvier 2002",
  LABO: "",
  LARC: "",
  LIEUX: "",
  LOCA: "Paris ; musée du Louvre département des Peintures",
  LOCA2: "France ; Ile-de-France ; Paris",
  LOCA3: "",
  MILL: ["1839"],
  MILU: "",
  MOSA: "",
  MSGCOM:
    "<A HREF='mailto:photo@rmn.fr?Subject=Commande&body=Bonjour,%0D%0A%0D%0AEn provenance de la base JOCONDE - Demande de photographie et/ou de conditions d'utilisation de :%0D%0APeinture : N'ENTREZ PAS / DIAZ DE LA PENA Narcisse%0D%0A%0D%0AMerci.'>Demande de photographie et/ou de conditions d'utilisation</A>",
  MUSEO: "M5031",
  NSDA: "",
  ONOM: [],
  PAUT: "Bordeaux, 1807 ; Menton, 1876",
  PDAT: "",
  PDEC: "",
  PEOC: [],
  PERI: ["2e quart 19e siècle"],
  PERU: [],
  PHOT:
    "© Gérard Blot#Réunion des musées nationaux - utilisation soumise à autorisation",
  PINS: "N. Diaz 39 (S.D.b.d.)",
  PLIEUX: "",
  PREP: [],
  PUTI: "",
  RANG: "",
  REDA: [],
  REFIM: "M503604_96DE11977_P.JPG,DS1,,004068.jpg",
  REPR: "scène (femme, conversation, putti, arcade)",
  RETIF: "",
  SREP: [],
  STAT: [
    "propriété de l'Etat",
    "legs",
    "musée du Louvre département des Peintures"
  ],
  TECH: ["peinture à l'huile, toile"],
  TICO: "DIAZ DE LA PENA Narcisse : N'ENTREZ PAS",
  TITR: "N'ENTREZ PAS",
  TOUT: "",
  UTIL: [],
  VIDEO: ["/0002/m503604_96de11977_p.jpg;/0002/m503604_96de11977_v.jpg"],
  WWW: "",
  LVID: "",
  _id: "5ba4f4feb0be2c41ccbeccfc",
  REF: "000PE001028",
  __v: 0
};
