module.exports = [
	"Auvergne-Rhône-Alpes",
	"Bourgogne-Franche-Comté",
	"Bretagne",
	"Centre-Val de Loire",
	"Corse",
	"Grand Est",
	"Guadeloupe",
	"Guyane",
	"Hauts-de-France",
	"Île-de-France",
	"La Réunion",
	"Martinique",
	"Mayotte",
	"Normandie",
	"Nouvelle-Aquitaine",
	"Occitanie",
	"Pays de la Loire",
	"Provence-Alpes-Côte d'Azur",
];
