//Modele joconde POP
// here is define all properties required by the app in differents view ( import, export, edition) . 
// Its more a settings file than a global state. 

export default [
    { value: "REF", export: true },
    { value: "REFMIS", export: true },
    { value: "ADPT", export: true },
    { value: "APPL", export: true },
    { value: "APTN", export: true },
    { value: "ATTR", export: true },
    { value: "AUTR", export: true },
    { value: "BIBL", export: true },
    { value: "COMM", export: true },
    { value: "CONTACT", export: true },
    { value: "COOR", export: true },
    { value: "COPY", export: true },
    { value: "DACQ", export: true },
    { value: "DATA", export: true },
    { value: "DATION", export: true },
    { value: "DDPT", export: true },
    { value: "DECV", export: true },
    { value: "DENO", export: true },
    { value: "DEPO", export: true },
    { value: "DESC", export: true },
    { value: "DESY", export: true },
    { value: "DIFFU", export: true },
    { value: "DIMS", export: true },
    { value: "DMAJ", export: true },
    { value: "DMIS", export: true },
    { value: "DOMN", export: true, thesaurus: 'http://data.culture.fr/thesaurus/resource/ark:/67717/T51', thesaurus_strict: true },
    { value: "DREP", export: true },
    { value: "ECOL", export: true, thesaurus: 'http://data.culture.fr/thesaurus/resource/ark:/67717/T517' },
    { value: "EPOQ", export: true, thesaurus: 'http://data.culture.fr/thesaurus/resource/ark:/67717/T93' },
    { value: "ETAT", export: true },
    { value: "EXPO", export: true },
    { value: "GENE", export: true },
    { value: "GEOHI", export: true },
    { value: "HIST", export: true },
    { value: "IMAGE", export: true },
    { value: "IMG", export: true },
    { value: "INSC", export: true },
    { value: "INV", export: true },
    { value: "LABEL", export: true },
    { value: "LABO", export: true },
    { value: "LARC", export: true },
    { value: "LIEUX", export: true },
    { value: "LOCA", export: true },
    { value: "LOCA2", export: true },
    { value: "LOCA3", export: true },
    { value: "MILL", export: true },
    { value: "MILU", export: true },
    { value: "MOSA", export: true },
    { value: "MSGCOM", export: true },
    { value: "MUSEO", export: true },
    { value: "NSDA", export: true },
    { value: "ONOM", export: true },
    { value: "PAUT", export: true },
    { value: "PDAT", export: true },
    { value: "PDEC", export: true },
    { value: "PEOC", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T521" },
    { value: "PERI", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T521" },
    { value: "PERU", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T521" },
    { value: "PHOT", export: true },
    { value: "PINS", export: true },
    { value: "PLIEUX", export: true },
    { value: "PREP", export: true },
    { value: "PUTI", export: true },
    { value: "RANG", export: true },
    { value: "REDA", export: true },
    { value: "REFIM", export: true },
    { value: "REPR", export: true },
    { value: "RETIF", export: true },
    { value: "SREP", export: true },
    { value: "STAT", export: true },
    { value: "TECH", export: true },
    { value: "TICO", export: true },
    { value: "TITR", export: true },
    { value: "TOUT", export: true },
    { value: "UTIL", export: true },
    { value: "VIDEO", export: true },
    { value: "WWW", export: true },
    { value: "LVID", export: true },
];