// here is define all properties required by the app in differents view ( import, export, edition) . 
// Its more a settings file than a global state. 

export default [
    { value: "REF", export: true },
    { value: "PRODUCTEUR", export: true },
    { value: "CONTIENT_IMAGE", export: true },
    { value: "POP_COORDINATES_POINT", export: true },
    { value: "POP_COORDINATES_POLYGON", export: true },
    { value: "POP_HAS_LOCATION", export: true },
    { value: "POP_DATE", export: true },
    { value: "TOUT", export: true },
    { value: "ACTU", export: true },
    { value: "ADRS", export: true },
    { value: "AFFE", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T97" },
    { value: "AIRE", export: true },
    { value: "APPL", export: true },
    { value: "APRO", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T98" },
    { value: "ARCHEO", export: true },
    { value: "AUTP", export: true },
    { value: "AUTR", export: true },
    { value: "CADA", export: true },
    { value: "CANT", export: true },
    { value: "COLL", export: true },
    { value: "COM", export: true },
    { value: "COOR", export: true },
    { value: "COORM", export: true },
    { value: "COPY", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T21" },
    { value: "COUV", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T26" },
    { value: "DATE", export: true },
    { value: "DBOR", export: true },
    { value: "DOMN", export: true },
    { value: "DENO", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T96" },
    { value: "DENQ", export: true },
    { value: "DEPL", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T14" },
    { value: "DESC", export: true },
    { value: "DIMS", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T11" },
    { value: "DMAJ", export: true },
    { value: "DMIS", export: true },
    { value: "DOSS", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T13" },
    { value: "DPRO", export: true },
    { value: "DPT", export: true },
    { value: "EDIF", export: true },
    { value: "ELEV", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T25" },
    { value: "ENER", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T27" },
    { value: "ESCA", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T29" },
    { value: "ETAG", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T23" },
    { value: "ETAT", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T30" },
    { value: "ETUD", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T68" },
    { value: "GENR", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T197" },
    { value: "HIST", export: true },
    { value: "HYDR", export: true },
    { value: "IMPL", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T12" },
    { value: "INSEE", export: true },
    { value: "INTE", export: true, thesaurus: "http://data.culture.fr/thesaurus/resource/ark:/67717/T33" },
    { value: "JATT", export: true },
    { value: "JDAT", export: true },
    { value: "LBASE2", export: true },
    { value: "LIEU", export: true },
    { value: "LOCA", export: true },
    { value: "MFICH", export: true },
    { value: "MOSA", export: true },
    { value: "MHPP", export: true },
    { value: "MICR", export: true },
    { value: "MURS", export: true },
    { value: "NBOR", export: true },
    { value: "NOMS", export: true },
    { value: "OBS", export: true },
    { value: "PAFF", export: true },
    { value: "PART", export: true },
    { value: "PARN", export: true },
    { value: "PDEN", export: true },
    { value: "PERS", export: true },
    { value: "PLAN", export: true },
    { value: "PLOC", export: true },
    { value: "PPRO", export: true },
    { value: "PREP", export: true },
    { value: "PROT", export: true },
    { value: "PSTA", export: true },
    { value: "REFE", export: true },
    { value: "REFO", export: true },
    { value: "REFP", export: true },
    { value: "REG", export: true },
    { value: "REMA", export: true },
    { value: "REMP", export: true },
    { value: "RENV", export: true },
    { value: "REPR", export: true },
    { value: "RFPA", export: true },
    { value: "SCLD", export: true },
    { value: "SCLE", export: true },
    { value: "SCLX", export: true },
    { value: "SITE", export: true },
    { value: "STAT", export: true },
    { value: "TECH", export: true },
    { value: "TICO", export: true },
    { value: "TOIT", export: true },
    { value: "TYPO", export: true },
    { value: "VERT", export: true },
    { value: "REFIM", export: true },
    { value: "IMG", export: true },
    { value: "VIDEO", export: true },
    { value: "DOSURL", export: true },
    { value: "DOSURLP", export: true },
    { value: "DOSADRS", export: true },
    { value: "LIENS", export: true },
    { value: "IMAGE", export: true },
    { value: "VISI", export: true },
    { value: "VOCA", export: true },
    { value: "VOUT", export: true },
    { value: "WEB", export: true },
    { value: "ZONE", export: true },
    { value: "THEM", export: true },
    { value: "ACMH", export: true },
    { value: "ACURL", export: true },
    { value: "WADRS", export: true },
    { value: "WCOM", export: true },
    { value: "WRENV", export: true },
    { value: "REFM", export: true },
    { value: "CONTACT", export: true },
    { value: "IDAGR", export: true },
    { value: "LMDP", export: true },
    { value: "PINT", export: true },
    { value: "DLAB", export: true },

];