// here is define all properties required by the app in differents view ( import, export, edition) . 
// Its more a settings file than a global state. 

export default [
    { value: "PRODUCTEUR", export: true },
    { value: "CONTIENT_IMAGE", export: true },
    { value: "REF", export: true },
    { value: "TOUT", export: true },
    { value: "AUTR", export: true },
    { value: "PAUT", export: true },
    { value: "ATTR", export: true },
    { value: "ECOL", export: true },
    { value: "TITR", export: true },
    { value: "ATIT", export: true },
    { value: "PTIT", export: true },
    { value: "DENO", export: true },
    { value: "DESC", export: true },
    { value: "DOMN", export: true },
    { value: "LOCA", export: true },
    { value: "INSC", export: true },
    { value: "MARQ", export: true },
    { value: "OBSE", export: true },
    { value: "ETAT", export: true },
    { value: "GENE", export: true },
    { value: "PROV", export: true },
    { value: "HIST", export: true },
    { value: "HIST2", export: true },
    { value: "HIST3", export: true },
    { value: "HIST4", export: true },
    { value: "HIST5", export: true },
    { value: "HIST6", export: true },
    { value: "SCLE", export: true },
    { value: "STYL", export: true },
    { value: "MILL", export: true },
    { value: "TECH", export: true },
    { value: "DIMS", export: true },
    { value: "VIDEO", export: true },
    { value: "INV", export: true },
    { value: "EXPO", export: true },
    { value: "BIBL", export: true },
    { value: "AATT", export: true },
    { value: "AUTI", export: true },
    { value: "CATE", export: true },
    { value: "NOTE", export: true },
    { value: "REDC", export: true },
    { value: "DREP", export: true },
    { value: "PREP", export: true },
    { value: "REPR", export: true },
    { value: "SREP", export: true },
    { value: "REFIM", export: true },
    { value: "DMAJ", export: true, generated: true, thesaurus: 'http://data.culture.fr/thesaurus/resource/ark:/67717/T51' },
    { value: "NUMS", export: true },
    { value: "SUITE", export: true },
    { value: "COMM", export: true },
    { value: "NOTE2", export: true },
    { value: "RESUME", export: true },
    { value: "PHOT", export: true },
];




/*
        "AFFE": "http://data.culture.fr/thesaurus/resource/ark:/67717/T97",
        "APRO": "http://data.culture.fr/thesaurus/resource/ark:/67717/T98",
        "COPY": "http://data.culture.fr/thesaurus/resource/ark:/67717/T21",
        "COUV": "http://data.culture.fr/thesaurus/resource/ark:/67717/T26",
        "DENO": "http://data.culture.fr/thesaurus/resource/ark:/67717/T96",
        "DEPL": "http://data.culture.fr/thesaurus/resource/ark:/67717/T14",
        "DIMS": "http://data.culture.fr/thesaurus/resource/ark:/67717/T11",
        "DOSS": "http://data.culture.fr/thesaurus/resource/ark:/67717/T13",
        "ELEV": "http://data.culture.fr/thesaurus/resource/ark:/67717/T25",
        "ENER": "http://data.culture.fr/thesaurus/resource/ark:/67717/T27",
        "ESCA": "http://data.culture.fr/thesaurus/resource/ark:/67717/T29",
        "ETAG": "http://data.culture.fr/thesaurus/resource/ark:/67717/T23",
        "ETAT": "http://data.culture.fr/thesaurus/resource/ark:/67717/T30",
        "ETUD": "http://data.culture.fr/thesaurus/resource/ark:/67717/T68",
        "GENR": "http://data.culture.fr/thesaurus/resource/ark:/67717/T197",
        "IMPL": "http://data.culture.fr/thesaurus/resource/ark:/67717/T12",
        "INTE": "http://data.culture.fr/thesaurus/resource/ark:/67717/T33",
*/