version: 2.1

commands:
  restore_node_modules:
    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  save_node_modules:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  configure_aws_ebcli:
    steps:
      - run: sudo pip install awsebcli
      - run:
          name: AWS credentials
          command: |
            mkdir ~/.aws
            echo "[eb-cli]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_node_modules
      - run: yarn install --frozen-lockfile
      - save_node_modules
  test:
    docker:
      - image: circleci/node:8.10
      - image: circleci/mongo:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_node_modules
      - run: yarn test
  deploy_eb_staging:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_node_modules
      - configure_aws_ebcli
      - run: eb deploy pop-api-staging
  deploy_eb_prod:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - restore_node_modules
      - configure_aws_ebcli
      - run: eb deploy pop-api

workflows:
  version: 2.1
  ci_cd:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_eb_staging:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_eb_prod:
          requires:
            - deploy_eb_staging
          filters:
            branches:
              only: master
