var mongoose = require('mongoose');
var mongoosePaginate = require('mongoose-paginate');
var mongoosastic = require('mongoosastic')
var getElasticInstance = require("../elasticsearch");

const Schema = new mongoose.Schema({
    POP_DOMAINE: String,
    REF: String,
    TOUT: String,
    LABO: String,
    ADPT: String,
    APTN: String,
    APPL: String,
    ATTR: String,
    AUTR: String,
    BIBL: String,
    COMM: String,
    CONTACT: String,
    COOR: String,
    COPY: String,
    DATA: String,
    DACQ: String,
    DDPT: String,
    DMAJ: String,
    DMIS: String,
    DREP: String,
    DESY: String,
    DECV: String,
    DENO: String,
    DESC: String,
    REPR: String,
    DIMS: String,
    DOMN: String,
    ECOL: String,
    EPOQ: String,
    ETAT: String,
    EXPO: String,
    GENE: String,
    HIST: String,
    IMAGE: String,
    IMG: String,
    LABEL: String,
    INSC: String,
    DEPO: String,
    LIEUX: String,
    GEOHI: String,
    LOCA: String,
    LOCA2: String,
    LOCA3: String,
    MILL: String,
    MILU: String,
    MUSEO: String,
    INV: String,
    NSDA: String,
    ONOM: String,
    PERI: String,
    PERU: String,
    PHOT: String,
    MSGCOM: String,
    PAUT: String,
    PDAT: String,
    PDEC: String,
    PINS: String,
    PLIEUX: String,
    PREP: String,
    PUTI: String,
    REDA: String,
    REFIM: String,
    PEOC: String,
    SREP: String,
    STAT: String,
    TECH: String,
    TITR: String,
    TICO: String,
    UTIL: String,
    VIDEO: String,
    WWW: String,
    MOSA: String,
    DATION: String,
    DIFFU: String,
    LARC: String,
    RANG: String,
    RETIF: String,
}, { collection: 'joconde' })

Schema.plugin(mongoosePaginate);
Schema.plugin(mongoosastic, {
    esClient: getElasticInstance(),
    index: 'pop',
    bulk: { size: 1000, delay: 1000 }
});


const object = mongoose.model("joconde", Schema);

module.exports = object;