var mongoose = require('mongoose');
var mongoosePaginate = require('mongoose-paginate');
var mongoosastic = require('mongoosastic')
var getElasticInstance = require("../elasticsearch");

const Schema = new mongoose.Schema({
    POP_HAS_IMAGE: { type: String, default: '' },
    REF: { type: String, index: true },
    IMG: [String],
    ADPT: [String],
    APPL: [String],

    APTN: String,
    ATTR: String,
    AUTR: String,
    BIBL: String,
    COMM: String,
    CONTACT: [String],
    COOR: String,
    COPY: String,
    DACQ: String,
    DATA: String,
    DATION: String,
    DDPT: String,
    DECV: String,
    DENO: [String],
    DEPO: String,
    DESC: String,
    DESY: String,
    DIFFU: String,
    DIMS: String,
    DMAJ: String,
    DMIS: String,
    DOMN: [String],
    DREP: String,
    ECOL: [String],
    EPOQ: [String],
    ETAT: [String],
    EXPO: String,
    GENE: [String],
    GEOHI: [String],
    HIST: String,
    IMAGE: String,
    IMG: [String],
    INSC: [String],
    INV: String,
    LABEL: String,
    LABO: String,
    LARC: String,
    LIEUX:: String,
    LOCA: String,
    LOCA2: String,
    LOCA3: String,
    MILL: [String],
    MILU: String,
    MOSA: String,
    MSGCOM: String,
    MUSEO: String,
    NSDA: String,
    ONOM: [String],
    PAUT: String,
    PDAT: String,
    PDEC: String,
    PEOC: [String],
    PERI: [String],
    PERU: [String],
    PHOT: String,
    PINS: String,
    PLIEUX: String,
    PREP: [String],
    PUTI: String,
    RANG: String,
    REDA: [String],
    REFIM: String,
    REPR: String,
    RETIF: String,
    SREP: [String],
    STAT: [String],
    TECH: [String],
    TICO: String,
    TITR: String,
    TOUT: String,
    UTIL: [String],
    VIDEO: String,
    WWW: [String],
    LVID: String,

}, { collection: 'joconde' })

Schema.plugin(mongoosePaginate);
Schema.plugin(mongoosastic, {
    esClient: getElasticInstance(),
    index: 'joconde',
    bulk: { size: 1000, delay: 1000 }
});

const object = mongoose.model("joconde", Schema);

module.exports = object;