var mongoose = require('mongoose');
const Schema = new mongoose.Schema({
    REF: String,
    TOUT: String,
    AUTR: String,
    PAUT: String,
    ATTR: String,
    ECOL: String,
    TITR: String,
    ATIT: String,
    PTIT: String,
    DENO: String,
    DESC: String,
    DOMN: String,
    LOCA: String,
    INSC: String,
    MARQ: String,
    OBSE: String,
    ETAT: String,
    GENE: String,
    PROV: String,
    HIST: String,
    HIST2: String,
    HIST3: String,
    HIST4: String,
    HIST5: String,
    HIST6: String,
    SCLE: String,
    STYL: String,
    MILL: String,
    TECH: String,
    DIMS: String,
    VIDEO: String,
    INV: String,
    EXPO: String,
    BIBL: String,
    AATT: String,
    AUTI: String,
    CATE: String,
    NOTE: String,
    REDC: String,
    DREP: String,
    PREP: String,
    REPR: String,
    SREP: String,
    REFIM: String,
    DMAJ: String,
    NUMS: String,
    SUITE: String,
    COMM: String,
    NOTE2: String,
    RESUME: String,
    PHOT: String,
    ATTR: String,
    AUTI: String,
}, { _id: false })

const object = mongoose.model("mnr_dmf", Schema)

module.exports = object;