var mongoose = require('mongoose');
var mongoosePaginate = require('mongoose-paginate');
var mongoosastic = require('mongoosastic')
var getElasticInstance = require("../elasticsearch");


const Schema = new mongoose.Schema({
    VIDEO: String,
    CONTACT: String,
    ACQU: String,
    ADRS: String,
    ADRS2: String,
    AFIG: [String],
    AIRE: String,
    APPL: String,
    ATEL: String,
    AUTP: String,
    AUTR: [String],
    BIBL: String,
    CANT: String,
    CATE: [String],
    COM: String,
    COM2: String,
    CONTACT: String,
    COOR: String,
    COORM: String,
    COPY: String,
    DATE: [String],
    DBOR: [String],
    DENO: [String],
    DENQ: [String],
    DEPL: String,
    DESC: String,
    DIMS: String,
    DMAJ: [String],
    DMIS: [String],
    DOMN: String,
    DOSADRS: String,
    DOSS: [String],
    DOSURL: String,
    DOSURLP: String,
    DPRO: String,
    DPT: String,
    EDIF: String,
    EDIF2: String,
    EMPL: String,
    EMPL2: String,
    ETAT: [String],
    ETUD: String,
    EXEC: String,
    EXPO: String,
    HIST: String,
    IDAGR: [String],
    IMAGE: String,
    IMG: String,
    IMPL: String,
    INSC: [String],
    INSEE: [String],
    INSEE2: String,
    INTE: String,
    JDAT: [String],
    LBASE2: String,
    LIENS: [String],
    LIEU: String,
    LMDP: String,
    LOCA: String,
    MATR: [String],
    MFICH: [String],
    MICR: String,
    MOSA: String,
    NART: String,
    NINV: String,
    NOMS: [String],
    NUMA: String,
    NUMP: String,
    OBS: String,
    ORIG: String,
    PAPP: String,
    PARN: [String],
    PART: [String],
    PDEN: [String],
    PDIM: String,
    PERS: [String],
    PETA: String,
    PHOTO: String,
    PINS: String,
    PINT: String,
    PLOC: String,
    PPRO: String,
    PREP: String,
    PROT: String,
    REFA: [String],
    REFE: [String],
    REFM: String,
    REFP: [String],
    REG: String,
    RENP: [String],
    RENV: [String],
    REPR: String,
    SCLD: [String],
    SCLE: [String],
    SCLX: [String],
    SOUR: String,
    STAD: [String],
    STAT: [String],
    STRU: [String],
    THEM: String,
    TICO: String,
    TITR: String,
    TOUT: String,
    VIDEO: [String],
    VOLS: String,
    WADRS: String,
    WCOM: String,
    WEB: String,
    WRENV: String,
    ZONE: String,
}, { collection: 'palissy' })

Schema.plugin(mongoosePaginate);
Schema.plugin(mongoosastic, {
    esClient: getElasticInstance(),
    index: 'palissy',
    bulk: { size: 1000, delay: 1000 }
});


const object = mongoose.model("palissy", Schema)

module.exports = object;