var mongoose = require('mongoose')
var mongoosePaginate = require('mongoose-paginate')
var mongoosastic = require('mongoosastic')
var getElasticInstance = require('../elasticsearch')

const Schema = new mongoose.Schema({
  PRODUCTEUR: { type: String, default: '' },
  CONTIENT_IMAGE: { type: String, default: '' },
  BASE: { type: String, default: 'Inventaire patrimoine mobilier (Palissy)' },
  MEMOIRE: [{ ref: String, url: String }],
  REF: { type: String, unique: true, index: true, trim: true },
  ACQU: { type: String, default: '' },
  ADRS: { type: String, default: '' },
  ADRS2: { type: String, default: '' },
  AFIG: { type: [String], default: [] },
  AIRE: { type: String, default: '' },
  APPL: { type: String, default: '' },
  ATEL: { type: String, default: '' },
  AUTP: { type: String, default: '' },
  AUTR: { type: [String], default: [] },
  BIBL: { type: String, default: '' },
  CANT: { type: String, default: '' },
  CATE: { type: [String], default: [] },
  COM: { type: String, default: '' },
  COM2: { type: String, default: '' },
  CONTACT: { type: String, default: '' },
  COOR: { type: String, default: '' },
  COORM: { type: String, default: '' },
  COPY: { type: String, default: '' },
  DATE: { type: [String], default: [] },
  DBOR: { type: [String], default: [] },
  DENO: { type: [String], default: [] },
  DENQ: { type: [String], default: [] },
  DEPL: { type: String, default: '' },
  DESC: { type: String, default: '' },
  DIMS: { type: String, default: '' },
  DMAJ: { type: String, default: '', es_type: "keyword" }, // The format of date is not a date object everywhere. I cant translate it to date without a deepclean
  DMIS: { type: String, default: '', es_type: "keyword" }, // The format of date is not a date object everywhere. I cant translate it to date without a deepclean
  DOMN: { type: String, default: '' },
  DOSADRS: { type: String, default: '' },
  DOSS: { type: [String], default: [] },
  DOSURL: { type: String, default: '' },
  DOSURLP: { type: String, default: '' },
  DPRO: { type: String, default: '' },
  DPT: { type: String, default: '' },
  EDIF: { type: String, default: '' },
  EDIF2: { type: String, default: '' },
  EMPL: { type: String, default: '' },
  EMPL2: { type: String, default: '' },
  ETAT: { type: [String], default: [] },
  ETUD: { type: String, default: '' },
  EXEC: { type: String, default: '' },
  EXPO: { type: String, default: '' },
  HIST: { type: String, default: '' },
  IDAGR: { type: [String], default: [] },
  IMAGE: { type: String, default: '' },
  IMG: { type: [String], default: [] },
  IMPL: { type: String, default: '' },
  INSC: { type: [String], default: [] },
  INSEE: { type: String, default: [] },
  INSEE2: { type: String, default: '' },
  INTE: { type: String, default: '' },
  JDAT: { type: [String], default: [] },
  LBASE2: { type: String, default: '' },
  LIENS: { type: [String], default: [] },
  LIEU: { type: String, default: '' },
  LMDP: { type: String, default: '' },
  LOCA: { type: String, default: '' },
  MATR: { type: [String], default: [] },
  MFICH: { type: [String], default: [] },
  MICR: { type: String, default: '' },
  MOSA: { type: String, default: '' },
  NART: { type: String, default: '' },
  NINV: { type: String, default: '' },
  NOMS: { type: [String], default: [] },
  NUMA: { type: String, default: '' },
  NUMP: { type: String, default: '' },
  OBS: { type: String, default: '' },
  ORIG: { type: String, default: '' },
  PAPP: { type: String, default: '' },
  PARN: { type: [String], default: [] },
  PART: { type: [String], default: [] },
  PDEN: { type: [String], default: [] },
  PDIM: { type: String, default: '' },
  PERS: { type: [String], default: [] },
  PETA: { type: String, default: '' },
  PHOTO: { type: String, default: '' },
  PINS: { type: String, default: '' },
  PINT: { type: String, default: '' },
  PLOC: { type: String, default: '' },
  PPRO: { type: String, default: '' },
  PREP: { type: String, default: '' },
  PROT: { type: String, default: '' },
  REFA: { type: [String], index: true, default: [] },
  REFE: { type: [String], default: [] },
  REFM: { type: String, default: '' },
  REFP: { type: [String], default: [] },
  REG: { type: String, default: '' },
  RENP: { type: [String], default: [] },
  RENV: { type: [String], default: [] },
  REPR: { type: [String], default: [] },
  SCLD: { type: [String], default: [] },
  SCLE: { type: [String], default: [] },
  SCLX: { type: [String], default: [] },
  SOUR: { type: String, default: '' },
  STAD: { type: [String], default: [] },
  STAT: { type: [String], default: [] },
  STRU: { type: [String], default: [] },
  THEM: { type: String, default: '' },
  TICO: { type: String, default: '' },
  TITR: { type: String, default: '' },
  TOUT: { type: String, default: '' },
  VIDEO: { type: [String], default: [] },
  VOLS: { type: String, default: '' },
  WADRS: { type: String, default: '' },
  WCOM: { type: String, default: '' },
  WEB: { type: String, default: '' },
  WRENV: { type: String, default: '' },
  ZONE: { type: String, default: '' }
}, { collection: 'palissy' })

Schema.pre('update', function (next, done) {
  switch (this.REF.substring(0, 2)) {
    case 'IM': this.PRODUCTEUR = 'Inventaire'; break
    case 'PM': this.PRODUCTEUR = 'Monument Historique'; break
    case 'EM': this.PRODUCTEUR = 'Etat'; break
    default: this.PRODUCTEUR = 'Null'; break
  }

  this.CONTIENT_IMAGE = this.IMG ? 'oui' : 'non'
  next()
})

Schema.plugin(mongoosePaginate)
Schema.plugin(mongoosastic, {
  esClient: getElasticInstance(),
  index: 'palissy',
  bulk: { size: 500, delay: 2000 }
})

const object = mongoose.model('palissy', Schema)

object.createMapping({
  "mappings": {
    "palissy": {
      "properties": {
        "TICO": { "type": "text", "analyzer": "french" },
        "TITR": { "type": "text", "analyzer": "french" },
        "DMIS": { "type": "text" },
        "DMAJ": { "type": "text" },
        "PRODUCTEUR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "CONTIENT_IMAGE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "BASE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "MEMOIRE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REF": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ACQU": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ADRS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ADRS2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "AFIG": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "AIRE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "APPL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ATEL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "AUTP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "AUTR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "BIBL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "CANT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "CATE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "COM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "COM2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "CONTACT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "COOR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "COORM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "COPY": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DATE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DBOR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DENO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DENQ": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DEPL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DESC": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DIMS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DOMN": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DOSADRS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DOSS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DOSURL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DOSURLP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DPRO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "DPT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EDIF": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EDIF2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EMPL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EMPL2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ETAT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ETUD": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EXEC": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "EXPO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "HIST": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "IDAGR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "IMAGE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "IMG": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "IMPL": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "INSC": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "INSEE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "INSEE2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "INTE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "JDAT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "LBASE2": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "LIENS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "LIEU": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "LMDP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "LOCA": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "MATR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "MFICH": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "MICR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "MOSA": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "NART": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "NINV": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "NOMS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "NUMA": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "NUMP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "OBS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ORIG": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PAPP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PARN": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PART": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PDEN": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PDIM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PERS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PETA": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PHOTO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PINS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PINT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PLOC": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PPRO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PREP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "PROT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REFA": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REFE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REFM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REFP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REG": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "RENP": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "RENV": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "REPR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "SCLD": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "SCLE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "SCLX": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "SOUR": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "STAD": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "STAT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "STRU": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "THEM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "TOUT": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "VIDEO": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "VOLS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "WADRS": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "WCOM": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "WEB": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "WRENV": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
        "ZONE": { "type": "text", "fields": { "keyword": { "type": "keyword" } } },
      }
    }
  }
}, function (err, mapping) {
  if (err) {
    console.log('error mapping created', err);
    return;
  }
})

module.exports = object
