module.exports = { 
  PRODUCTEUR: "MUSEE",
  BASE: "Collections des musées de France (Joconde)",
  CONTIENT_IMAGE: "oui",
  REFMIS: "",
  ADPT: "",
  APPL: "",
  APTN: "",
  ATTR: "",
  AUTR: [],
  BIBL: "Registre d'inventaire muséographique (Registre n 1, p. 84 (sans date)",
  COMM: "",
  CONTACT: "musee@mairie-valence.fr",
  COOR: "Marina Zveguinzoff",
  COPY: "© musée des Beaux-Arts de Valence, 1999, © Direction des musées de France",
  DACQ: "",
  DATA: "",
  DATION: "",
  DDPT: "",
  DECV: "France ; Drôme ; Valence (Lieu de découverte) ; découverte fortuite",
  DENO: ["chapiteau"],
  DEPO: [],
  DESC: "Chapiteau sculpté sur trois faces, probablement des feuilles d'acanthe. Des entailles en triangle rectangle dont visibles sur le haut du tailloir. L'objet est très usé.",
  DESY: "",
  DIFFU: "non",
  DIMS: "H. 29 , LA. 19 (à la base) , LA. 30 (au sommet) ; P. 24",
  DMAJ: "",
  DMIS: "1999-12-06",
  DOMN: ["archéologie", "médiéval", "sculpture"],
  DREP: "",
  ECOL: [],
  EPOQ: ["moyen âge"],
  ETAT: "Mauvais état; Manque : pointes des feuilles d'acanthe.",
  EXPO: "",
  GENE: [],
  GEOHI: [],
  HIST: "Architecture",
  IMAGE: "oui",
  IMG: ["joconde/09880004268/999chap03941.jpg"],
  INSC: [],
  INV: "AR. 135",
  LABEL: "Musée de France#au sens de la loi n°2002-5 du 4 janvier 2002",
  LABO: "",
  LARC: "",
  LIEUX: [],
  LOCA: "Valence ; musée des beaux-arts",
  LOCA2: "France ; Rhône-Alpes ; Drôme",
  LOCA3: "",
  MILL: [],
  MILU: "",
  MOSA: "",
  MSGCOM: "<A HREF='mailto:info@musee-valence.org?Subject=Commande&body=Bonjour,%0D%0A%0D%0AEn provenance de la base JOCONDE - Demande de photographie et/ou de conditions d'utilisation de :%0D%0Aarchéologie ; médiéval ; sculpture. - N°INV=AR. 135%0D%0A%0D%0AMerci.'>Demande de photographie et/ou de conditions d'utilisation</A>",
  MUSEO: "M5031",
  NSDA: "",
  ONOM: [],
  PAUT: "",
  PDAT: "",
  PDEC: "Dans le registre méthodique n 1 : 'chapiteau trouvé à Valence'.",
  PEOC: [],
  PERI: [],
  PERU: [],
  PHOT: "© Nicolas Porte",
  PINS: "Numéro d'inventaire 135 en chiffres arabes, sur la face avant",
  PLIEUX: "",
  PREP: "",
  PUTI: "",
  RANG: "",
  REDA: [],
  REFIM: "M098801_999CHAP03941_P.JPG,DS1,,M0988_999CHAP03941_P.jpg",
  REPR: ["ornement à forme végétale"],
  RETIF: "",
  SREP: [],
  STAT: [],
  TECH: ["molasse", "taillé"],
  TICO: "chapiteau",
  TITR: "",
  TOUT: "",
  UTIL: [],
  VIDEO: ["/arc/0001/m098801_999chap03941_p.jpg", "/arc/0001/m098801_999chap03941_v.jpg"],
  WWW: ["http", "//www.rhone-alpes.culture.gouv.fr/museesdefrance/"],
  LVID: "",
  REF: "000PE001028",
  POP_CONTIENT_GEOLOCALISATION: "oui",
  POP_COORDONNEES: {
      lat: 44.931125,
      lon: 4.889563
  },
  DPT: "Drôme",
  NOMOFF: "musée des beaux-arts et d’archéologie",
  REGION: "Auvergne-Rhône-Alpes",
  VILLE_M: "Valence",
  REFMEM: [],
  REFPAL: [],
  REFMER: [],
  POP_IMPORT: []
}