module.exports = {
  PRODUCTEUR: "CAOA",
  CONTIENT_IMAGE: "oui",
  TOUT: "",
  ADRESSE: "Chasseigne (la)",
  AUTOEU: [""],
  AUTG: [""],
  AUTP: ["Richard, Christian"],
  AUTOR: [""],
  AUTTI: [""],
  COM: ["Thollet"],
  DOM: ["archéologie"],
  EDIF: "villa",
  EXPO: "",
  JDATPV: "",
  LIEUCOR: "",
  COTECOR: [""],
  LIEUCTI: "",
  COTECTI: "",
  LIEUCP: "",
  COTECP: "",
  LEG: "",
  OBJT: "",
  OBS: "",
  OBSOR: "",
  OBSTI: "",
  PAYS: [""],
  PUBLI: "",
  TIREDE: "",
  ROLE: "",
  PRECOR: "photographie aérienne",
  SERIE: "",
  THEATRE: "",
  TITRE: "Notice pour Test",
  DMAJ: "",
  DMIS: "2002-04-18",
  IDPROD: "service régional d'Archéologie Poitou-Charentes",
  NUMCD: "ARR54_005109_E_1",
  NUMF: "",
  INSEE: ["86270"],
  NVD: "",
MARQ: "",
  PLOC: "",
  ACQU: "",
  ADPHOT: "",
  AIRE: "",
  ANUMP: "",
  COPY: "© C. Richard",
  COULEUR: "OUI",
  DPT_LETTRE: "",
  DATIMM: "1997",
  DATOEU: [""],
  DATPV: "1997",
  DATOR: "",
  DATTI: "",
  DATG: "",
  DATD: "",
  DIFF: "reproduction soumise à autorisation du titulaire des droits d'exploitation",
  DPT: ["86"],
  EDIARCH: "villa",
  ECH: "",
  FORMAT: "Z",
  FORMATOR: "",
  FORMATTI: "",
  LBASE: ["9946"],
  WEB: "VISMEM-ARR54-PHOTAERIENNE",
  LIB: "",
  LOCA: "France ; Poitou-Charentes ; Vienne ; Thollet",
  LIEUORIG: "",
  MCGEO: "",
  MCL: [""],
  MENTIONS: "",
  MENTOR: "",
  MENTTI: "",
  MCPER: [""],
  VUECD: "ARR54_978609358ZA_2.TIF ; ARR54_978609358ZA_P.JPG ; VIG/ARR54_978609358ZA_V.JPG",
  NUMAUTP: "",
  NUMVERS: "",
  ANUMOR: "",
  NUMOR: "",
  NUMP: "",
  ANUMTI: "",
  NUMTI: "",
  RENV: "",
  REG: ["Poitou-Charentes"],
SENS: "",
  SCLE: [""],
  SUP: "",
  TECH: "",
  TECHOR: "",
  TECHTI: "",
  CINEPROD: "",
  TYP: "AREF",
  TYPDOC: "phototype argentique",
  TYPEIMG: "JPG ; Oui",
  TYPSUPP: "DS1",
  VIDEO: "mem/0303/arr54_978609358za_p.jpg;mem/0303/arr54_978609358za_v.jpg",
  LBASE2: "",
  LEG2: "",
  REFIM: "ARR54_978609358ZA_P.JPG,DS1,,",
  REFIMG: "",
  MOSA: "",
  SITE: "",
  NUMSITE: "86270001",
  NUMOP: "",
  CHRONO: "Gallo-romain",
  STRUCT: "bâtiment",
  SUJET: "",
  TICO: "",
  NUMI: "978609358ZA",
  LIEU: "",
  WADRS: "",
  CONTACT: "",
  EMET: "",
  NUM: "09358",
  IMG: "memoire/978609358ZA/arr54_978609358za_p.jpg",
  WCOM: "Thollet",
  LIENS: "",
  LAUTP: "",
  REF: "978601295ZA",
  MEMOIRE: [],
  BASE: "Photographies (Mémoire)",
  POP_COMMENTAIRES: ["Le champ CONTACT ne doit pas être vide", "Lien LBASE corrompu 9946"],
  POP_FLAGS: ["CONTACT_EMPTY", "LEG_EMPTY", "LBASE_LENGTH_EXACT_10", "LBASE_INVALID"],
  REFJOC: [],
  REFMUS: []
};
