module.exports = {
  BASE: "Photographies (Mémoire)",
  CONTIENT_IMAGE: "oui",
  POP_COMMENTAIRES: ["Le champ CONTACT ne doit pas être vide", "Lien LBASE corrompu 2008"],
  POP_IMPORT: [],
  TOUT: "",
  ADRESSE: "Guet (le)",
  AUTOEU: "",
  AUTG: "",
  AUTP: "Richard, Christian",
  AUTOR: "",
  AUTTI: "",
  COM: "Chauvigny",
  DOM: "archéologie",
  EDIF: "villa",
  EXPO: "",
  JDATPV: "",
  LIEUCOR: "",
  COTECOR: "",
  LIEUCTI: "",
  COTECTI: "",
  LIEUCP: "",
  COTECP: "",
  LEG: "Villa avec cour intérieure",
  OBJT: "",
  OBS: "",
  OBSOR: "",
  OBSTI: "",
  PAYS: "",
  PUBLI: "",
  TIREDE: "",
  ROLE: "",
  PRECOR: "photographie aérienne",
  SERIE: "",
  THEATRE: "",
  TITRE: "",
  DMAJ: "",
  DMIS: "2002-04-18",
  IDPROD: "service régional d'Archéologie Poitou-Charentes",
  NUMCD: "ARR54_005026_E",
  NUMF: "",
  INSEE: "86070",
  NVD: "",
  MARQ: "",
  ACC: "",
  ACQU: "",
  ADPHOT: "",
  AIRE: "",
  ANUMP: "",
  COPY: "© C. Richard",
  COULEUR: "OUI",
  COSTUME: "",
  DATIMM: "99",
  DATOEU: "",
  DATPV: "1997",
  DATOR: "",
  DATTI: "",
  DATG: "",
  DATD: "",
  DIFF: "reproduction soumise à autorisation du titulaire des droits d'exploitation",
  DPT: "86",
  EDIARCH: "villa",
  ECH: "",
  FORMAT: "Z",
  FORMATOR: "",
  FORMATTI: "",
  LBASE: ["2008"],
  WEB: "VISMEM-ARR54-PHOTAERIENNE",
  LIB: "",
  LOCA: "France ; Poitou-Charentes ; Vienne ; Chauvigny",
  LIEUORIG: "",
  MCGEO: "",
  MCL: "",
  MENTIONS: "",
  MENTOR: "",
  MENTTI: "",
  MCPER: "",
  VUECD: "ARR54_978601295ZA_2.TIF ; ARR54_978601295ZA_P.JPG ; ARR54_978601295ZA_V.JPG",
  NUMAUTP: "",
  NUMCAF: "",
  ANUMOR: "",
  NUMOR: "",
  NUMP: "",
  ANUMTI: "",
  NUMTI: "",
  RENV: "",
  REG: "Poitou-Charentes",
  SENS: "",
  SCLE: "",
  SUP: "",
  TECH: "",
  TECHOR: "",
  TECHTI: "",
  TOILE: "",
  TYP: "A",
  TYPDOC: "phototype argentique",
  TYPEIMG: "JPG ; Oui",
  TYPSUPP: "DS1",
  VIDEO: "mem/0303/arr54_978601295za_p.jpg;mem/0303/arr54_978601295za_v.jpg",
  LBASE2: "",
  LEG2: "",
  REFIM: "ARR54_978601295ZA_P.JPG,DS1,,",
  REFIMG: "",
  MOSA: "",
  SITE: "",
  NUMSITE: "86070041",
  NUMOP: "",
  CHRONO: "Gallo-romain",
  REPRO: "",
  STRUCT: "bâtiment",
  SUJET: "",
  TICO: "",
  NUMI: "978601295ZA",
  LIEU: "",
  ADRS: "",
  CONTACT: "",
  EMET: "",
  NUM: "01295",
  IMG: "memoire/978601295ZA/arr54_978601295za_p.jpg",
  WCOM: "Chauvigny",
  LIENS: "",
  LAUTP: "",
  TRL: "",
  DENO: "",
  AUT: "",
  AUTR: "",
  DOC: "",
  NUMG: "",
  NOMSN: "",
  REF: "978601295ZA",
  MEMOIRE: []
};
