module.exports = {
  POP_COORDONNEES: { lat: 0, lon: 0 },
  POP_COORDINATES_POLYGON: { type: "Polygon", coordinates: [] },
  BASE: "Patrimoine architectural (Mérimée)",
  CONTIENT_IMAGE: "non",
  POP_FLAGS: [],
  POP_CONTIENT_GEOLOCALISATION: "non",
  POP_DATE: [],
  POP_IMPORT: ["5cb19026bf7f212b8a6881de"],
  TOUT: "",
  ACTU: "",
  ADRS: "",
  AFFE: "",
  AIRE: "",
  APPL: "",
  APRO: [],
  ARCHEO: "",
  AUTP: [],
  AUTR: [],
  CADA: [],
  CANT: "",
  COLL: [],
  COM: "Tsingoni",
  COOR: "",
  COORM: "",
  COPY: ["(c) Monuments historiques"],
  COUV: [],
  DATE: [],
  DBOR: "",
  DOMN: [],
  DENO: ["mosquet", "minaret"],
  DENQ: "",
  DEPL: "",
  DESC: "",
  DIMS: "",
  DMAJ: "2019-04-13",
  DMIS: "2019-04-13",
  DOSS: "dossier individuel",
  DPRO: "2017/04/07 : classé MH",
  DPT: "976",
  EDIF: "",
  ELEV: [],
  ENER: [],
  ESCA: [],
  ETAG: [],
  ETAT: [],
  ETUD: [],
  GENR: [],
  HIST: "",
  HYDR: "",
  IMPL: [],
  INSEE: "97617",
  INTE: [],
  JATT: [],
  JDAT: [],
  LBASE2: "",
  LIEU: "",
  LOCA: "",
  MFICH: "",
  MOSA: "",
  MHPP: "",
  MICR: "",
  MURS: [],
  NBOR: "",
  NOMS: [],
  OBS: "",
  PAFF: "",
  PART: [],
  PARN: [],
  PDEN: "édifice religieux non chrétien",
  PERS: [],
  PLAN: "",
  PLOC: "",
  PPRO: "Le minaret de la Mosquée de Tsingoni",
  PREP: [],
  PROT: [],
  PSTA: "",
  REFE: [],
  REFP: [],
  REFO: [],
  REFJOC: [],
  REFMUS: [],
  REG: "Mayotte",
  REMA: "",
  REMP: "",
  RENV: [],
  REPR: "",
  RFPA: "",
  SCLD: [],
  SCLE: [],
  SCLX: [],
  SITE: "",
  STAT: "propriété du département",
  TECH: [],
  TICO: "Minaret de la Mosquée",
  TOIT: [],
  TYPO: "",
  VERT: "",
  REFIM: "",
  IMG: [],
  VIDEO: "",
  DOSURL: "",
  DOSURLPDF: "",
  DOSADRS: "",
  LIENS: [],
  IMAGE: "",
  VISI: [],
  VOCA: "",
  VOUT: [],
  WEB: "",
  ZONE: "",
  THEM: "",
  ACMH: "",
  ACURL: "",
  WADRS: "",
  WCOM: "Tsingoni",
  WRENV: "",
  REFM: "",
  CONTACT: "mediatheque.patrimoine@culture.gouv.fr",
  IDAGR: "",
  LMDP: "",
  PINT: "",
  DLAB: "",
  REF: "PA97600007",
  MEMOIRE: []
};
