module.exports = {
  POP_COORDINATES_POINT: {
    type: "Point",
    coordinates: []
  },
  POP_COORDINATES_POLYGON: {
    type: "Polygon",
    coordinates: []
  },
  PRODUCTEUR: "Monuments Historiques",
  CONTIENT_IMAGE: "non",
  POP_HAS_LOCATION: ["non"],
  POP_DATE: [1400, 1500],
  TOUT: "",
  ACTU: "",
  ADRS: "Dans le cimetière",
  AFFE: "",
  AIRE: "",
  APPL: "",
  APRO: ["arrêté"],
  ARCHEO: "",
  AUTP: [],
  AUTR: [],
  CADA: ["AC 4"],
  CANT: "",
  COLL: [],
  COM: ["Aix-en-Othe"],
  COOR: "",
  COORM: "",
  COPY: ["© Monuments historiques, 1992"],
  COUV: [],
  DATE: [],
  DBOR: "1992",
  DOMN: [],
  DENO: ["chapelle"],
  DENQ: "",
  DEPL: "",
  DESC: "",
  DIMS: "",
  DMAJ: "2019-05-15",
  DMIS: "1993-03-29",
  DOSS: "Dossier de protection",
  DPRO: "1975/01/28 : inscrit MH",
  DPT: ["10"],
  EDIF: "",
  ELEV: [],
  ENER: [],
  ESCA: [],
  ETAG: [],
  ETAT: ["désaffecté"],
  ETUD: ["recensement immeubles MH"],
  GENR: [],
  HIST: "",
  HYDR: "",
  IMPL: [],
  INSEE: ["10003"],
  INTE: ["A signaler"],
  JATT: [],
  JDAT: [],
  LBASE2: "",
  LIEU: "",
  LOCA: "",
  MFICH: "",
  MOSA: "",
  MHPP: "",
  MICR: "",
  MURS: [],
  NBOR: "10000001",
  NOMS: [],
  OBS: "",
  PAFF: "",
  PART: [],
  PARN: [],
  PDEN: "",
  PERS: [],
  PLAN: "",
  PLOC: "Anciennement région de : Champagne-Ardenne",
  PPRO: "Chapelle Saint-Avit (cad. AC 4) : inscription par arrêté du 28 janvier 1975",
  PREP: [],
  PROT: ["inscrit MH"],
  PSTA: "",
  REFE: [],
  REFP: [],
  REFO: [],
  REG: ["Grand Est"],
  REMA: "",
  REMP: "",
  RENV: [],
  REPR: "",
  RFPA: "",
  SCLD: [],
  SCLE: ["15e siècle", "16e siècle"],
  SCLX: ["15e s.", "16e s."],
  SITE: "",
  STAT: "propriété de la commune",
  TECH: [],
  TICO: "Chapelle Saint-Avit",
  TOIT: [],
  TYPO: "",
  VERT: "",
  REFIM: "",
  IMG: [],
  IDEO: "",
  DOSURL: "",
  DOSURLP: "",
  DOSADRS: "",
  LIENS: [],
  IMAGE: "",
  VISI: [],
  VOCA: "",
  VOUT: [],
  WEB: "",
  ZONE: "",
  THEM: "",
  ACMH: "",
  ACURL: "",
  WADRS: "Dans le cimetière",
  WCOM: ["Aix-en-Othe"],
  WRENV: "",
  REFM: "",
  CONTACT: "mediatheque.patrimoine@culture.gouv.fr",
  IDAGR: "I53136",
  LMDP: "",
  PINT: "",
  DLAB: "",
  REF: "PA00078014",
  MEMOIRE: [],
  BASE: "Patrimoine architectural (Mérimée)",
  DOSURLPDF: "",
  POP_CONTIENT_GEOLOCALISATION: "non",
  POP_COORDONNEES: {
    "lat": 0,
    "lon": 0
  },
  POP_IMPORT: [],
  DPT_LETTRE: ["Aube"],
  POP_ARRETE_PROTECTION: [],
  POP_DOSSIER_PROTECTION: [],
  POP_DOSSIER_VERT: "",
  POP_FLAGS: [],
  REFJOC: [],
  REFMUS: []
};
