module.exports = {
	  PRODUCTEUR: "MNR",
    CONTIENT_IMAGE: "oui",
    NET: "Présence sur site internet du musée ; date",
    AUTR: ["Anonyme"],
    PAUT: "",
    ATTR: "",
    ECOL: "",
    TITR: "Statuette d'Isis allaitant Horus",
    ATIT: "",
    PTIT: "",
    DENO: ["Statuette"],
    DESC: "Isis est assise sur un siège cubique à pilier dorsal. La déesse porte une perruque tripartite à uraeus (serpent dressé) et sa couronne (un disque solaire encadré, à l'origine, de cornes de vache) repose sur un modius décoré d'uraeus. Isis tient sur ses genoux le dieu enfant Horus, nu, qu'elle allaite. La tête d'Horus a disparu, mais il reste un fragment de mèche de l'enfant, sa coiffure habituelle pour ce type d'objet. Il n'y a aucune trace d'inscription.",
    DOMN: ["Antiquités égyptiennes ; sculpture"],
    LOCA: "Besançon ; musée des beaux-arts et d'archéologie",
    INSC: "",
    MARQ: "Sous le socle : 34 759 : numéro du Central Collecting Point de Munich.#D. 951.5.1 : numéro de dépôt au Musée des beaux-arts et d'archéologie de Besançon.#A l'arrière du socle, en haut et à gauche : étiquette collée, fragmentaire et illisible.",
    OBSE: "",
    ETAT: "La tête d'Horus manque ; la main et une partie de l'avant-bras gauches d'Isis sont brisés ; la coiffure est mutilée.",
    GENE: "Epoque gréco-romaine, basse époque",
    PROV: "",
    HIST: "D'après les recherches menées jusqu'à présent, l'historique de la statuette d'Isis, avant guerre, est inconnu.#La statuette a été achetée 60 000 francs, à Paris, par Walter Bornheim, pour sa galerie munichoise, 13 Briennerstrasse, auprès du marchand A. Garabed. Elle figure, en effet, sur une facture d'A. Garabed, daté du 19 mai 1941, à Paris, sous le titre « basaltfigur sitzenden Isis aeg. » (1)#Bornheim explique, dans un courrier à la commission de récupération artistique, le 14 juin 1946 : « La galerie des anciennes Art (sic) possède entre autre : 1°-Une petite figurine égyptienne à 20 cm de haut représentant \"Isis\" assise, que j'avais envoyée au choix à un client munichois avant la fin de la guerre. Je vais la faire chercher ces jours pour qu'elle vous soit remise » (2).#Dans un dossier rassemblant les factures des achats que Bornheim a réalisés en France en 1941, deux documents mentionnent une Isis. Nous avons retenu celui pour lequel le matériau correspond à notre objet.#Conservée dans le Central Collecting Point de Munich depuis le 16 juillet 1946 ou le 9 juillet, selon les documents (3), elle est rapatriée en France non par le dix-huitième convoi en provenance de Munich comme prévu (4), mais par le vingt-et-unième convoi en provenance de Munich le 25 septembre 1947, sous le titre erroné «Isis and Poms», en bronze (n° d'ordre 442 ; n° d'ordre français 12 868 ; n° d'arrivée à Munich 34 759/ « Mchn. Briennerstr.1 [sic] ») (5). Le propriétaire est toujours \"inconnu\". Sur un document énumérant le contenu de la caisse XIX/63  où se trouvait la statuette d'Isis, il est précisé : « retrouvé caisse D.W. », initiales des David-Weill, bien que cet objet provienne du marché de l'art (6). Aucune mention de cette oeuvre n'a été relevée dans les dossiers concernant la famille David-Weill. #Retenue lors de la première commission de choix des oeuvres de la récupération artistique du 27 octobre 1949 (7), la statuette est attribuée aux musées nationaux (musée du Louvre, département des Antiquités égyptiennes du musée du Louvre) en 1951 (8). Le musée du Louvre l'a déposée au musée des beaux-arts et d'archéologie de Besançon la même année (numéro de dépôt D.951.5.1) (9).",
    HIST2: "",
    HIST3: "",
    HIST4: "",
    SALLES: "Exposé en salles, à telle date",
    CARTELS: "Formulation des cartels (fautive ou non, à telle date)",
    SCLE: [],
    STYL: "Basse époque",
    MILL: "",
    TECH: ["Pierre (Grauwacke noir : basalte) ; ronde-bosse"],
    DIMS: ["H. 0,158 ; La. 0,047 ; P. 0,082 m."],
    VIDEO: ["mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-dos_detail.jpg", "mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-face-detail.jpg", "mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-profil-droit-detail.jpg", "mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-profil-gauche-detail.jpg", "mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-quart-detail.jpg", "mnr/AEG00001/ER1-copyright_Besancon_musee_des_Beaux-Arts_et_d_Archeologie_Dorit_Barzel-D_951-5-1-socle-detail.jpg", "mnr/AEG00001/ER01-vue2-copyright_droits_reserves.jpg", "mnr/AEG00001/ER01-vue3-copyright_droits_reserves.jpg", "mnr/AEG00001/ER01-vue4-copyright_droits_reserves.jpg", "mnr/AEG00001/ER01-vue5-copyright_droits_reserves.jpg", "mnr/AEG00001/ER01-vue6-copyright_droits_reserves.jpg", "mnr/AEG00001/ER01-vue7-copyright_droits_reserves.jpg", "mnr/AEG00001/egypt01n.jpg", "mnr/AEG00001/ER1D_951_5_1_copyright_Musee_du_Louvre_face2.jpg", "mnr/AEG00001/ER1D_951_5_1_copyright_Musee_du_Louvre_profil.jpg"],
    INV: "ER 1",
    EXPO: "1990 (15 septembre - 3 décembre), Besançon, Musée des Beaux-Arts et d'Archéologie, \"Loin du sable. Collections égyptiennes du Musée des Beaux-Arts et d'Archéologie de Besançon\" (Cat. : p. 151, n° 210, repr.).",
    BIBL: "GASSE, Annie, « Musée des beaux-arts et d'archéologie de Besançon. Guide des collections égyptiennes », Besançon, 1991, fig. 28, non paginé.",
    AATT: "",
    AUTI: "",
    CATE: "Oeuvre dont l'historique est incomplet entre 1933 et 1945, en l'état des recherches actuelles.",
    RCL: "Récolé, date",
    NOTE: "(1)MEAE/209SUP218 34A : Liste des objets rendus par Bornheim - MEAE/209SUP913 : Reçus de tableaux vendus à Bornheim par divers marchands en 1941. #(2)MEAE/209SUP482 P167 : Traduction de la lettre de Walter Bornheim du 14 juin 1946. #(3)NARA/RG Ardelia Hall collection box 528 : «Property Card» ; NARA/RG 260 Ardelia Hall Collection box 280, folder 4 : «Diary In-Shipments. MCCP cultural objects movement and control record, 1945-1949». #(4)MEAE/209SUP236 A44 : Lettre de Michel Florisoone, chef des Services administratifs de la commission de récupération artistique, au capitaine E. J. B. Doubinsky, Mission française des restitutions à Francfort, le 17 septembre 1947. #(5)MEAE/209SUP114 A47 : \"Schedule A. List of French Property from Central Collecting Point\", Munich. vingt-et-unième convoi, le 25 septembre 1947 ; MEAE/209SUP832 : Fichier de la récupération artistique. #(6)MEAE/209SUP441 : Cahier manuscrit inventoriant les objets à la réception des convois. #(7)MEAE/209SUP710 R39 : Tableau préparatoire à la première commission de choix des oeuvres de la récupération artistique ; MEAE/209SUP446 : Compte-rendu de la séance du jeudi 27 octobre 1949 de la première commission de choix des oeuvres de la récupération artistique.#(8)Musée du Louvre, département des Antiquités égyptiennes, documentation : Arrêté d'attribution du ministère de l'Education nationale du 16 mai 1951. #(9)Musée du Louvre, département des Antiquités égyptiennes, documentation : Arrêté du ministère de l'Education nationale du 17 février 1951.",
    REDC: ["C.O. ; A.-E. D.-V. ; N. M.-S. ; F.G."],
    DREP: "",
    PREP: "",
	  REPR: "",
    SREP: "",
    REFIM: "",
    DMAJ: "2020-05-18",
    NUMS: "D.951.5.1 : numéro de dépôt des musées de Besançon",
    SUITE: "",
    COMM: "Champ Catégorie renseigné d'après les données de la mission Matteoli.",
    NOTE2: "",
    RESUME: "",
    PHOT: "© Réunion des musées nationaux Grand Palais.\n© Besançon, musée des beaux-arts et d'archéologie Dorit Barzel.",
    REF: "AEG00001",
    AFFE: "Paris ; musée du Louvre ; département des Antiquités égyptiennes",
    BASE: "Récupération artistique (MNR Rose-Valland)",
    DMIS: "",
    POP_IMPORT: [],
    POP_COMMENTAIRES: [],
    POP_FLAGS: []
};
