module.exports = {
  PRODUCTEUR: "MNR",
  BASE: "Récupération artistique (MNR Rose-Valland)",
  CONTIENT_IMAGE: "oui",
  POP_COMMENTAIRES: [],
  POP_IMPORT: [],
  TOUT: "",
  AUTR: ["Anonyme"],
  PAUT: "",
  ATTR: "",
  ECOL: "France",
  TITR: "Cassette",
  ATIT: "Cassette rectangulaire cuir rouge",
  PTIT: "",
  DENO: [],
  DESC: "Cassette rectangulaire,",
  DOMN: ["Objets d'art ; maroquinerie"],
  LOCA: "Compiègne ; musée national de la Voiture et du Tourisme",
  INSC: "",
  MARQ: "Ancien numéro 28.",
  OBSE: "",
  ETAT: "",
  GENE: "",
  PROV: "",
  HIST: "L'OAR 308 a pu être id",
  HIST2: "",
  HIST3: "",
  HIST4: "",
  HIST5: "",
  HIST6: "",
  SCLE: ["Fin 17e siècle ?"],
  STYL: "",
  MILL: "",
  TECH: ["Ebénisterie ; cuir ; dorure"],
  DIMS: ["H. 0,29 ; La. 0,43 ; P. 0,22 m"],
  VIDEO: [
    "mnr/OAR00308/1020705n.jpg",
    "mnr/OAR00308/OAR308-copyright_Musee_du_Louvre-departement_des_Objets_d_art.jpg"
  ],
  INV: "OAR 308",
  EXPO: "1997 (9 avril-5 mai), Paris, musée du Louvre, ",
  BIBL: "Catalogue de l'exposition \"Présentation des oeuvres récupérées après la S",
  AATT: "",
  AUTI: "",
  CATE:
    "Oeuvre dont l'historique est incomplet entre 1933 et 1945, en l'état des recherches actuelles.",
  CATE_DEPREC: "",
  NOTE: "(1)MEAE/209SUP372 P3 : Liste des objets d'art localisés dans le Deuts",
  REDC: ["M.B./F.G."],
  DREP: "",
  PREP: "",
  REPR: "",
  SREP: "",
  REFIM: "",
  DMAJ: "2018-12-17",
  DMIS: "",
  AFFE: "Paris ; musée du Louvre ; département des Objets d'art",
  NUMS: "",
  SUITE: "",
  COMM: "Champ Catégorie renseigné d'après les données de la mission Matteoli",
  NOTE2: "",
  RESUME: "",
  PHOT:
    "© Réunion des musées nationaux Grand Palais.# (C) Musée du Louvre, département des Objets d'art.",
  REF: "OAR00308"
};
