module.exports = {
  POP_COORDONNEES: { lat: 0, lon: 0 },
  POP_COORDINATES_POLYGON: { type: "Polygon", coordinates: [] },
  CONTIENT_IMAGE: "non",
  POP_COMMENTAIRES: [],
  POP_CONTIENT_GEOLOCALISATION: "non",
  BASE: "Patrimoine mobilier (Palissy)",
  POP_IMPORT: [],
  ACQU: "",
  ADRS: "",
  ADRS2: "",
  AFIG: [],
  AIRE: "",
  APPL: "",
  ATEL: "",
  AUTP: "",
  AUTR: ["Franché Cyril (constructeur)"],
  BIBL: "",
  CANT: "",
  CATE: ["patrimoine maritime"],
  COM: "Saint-Pierre",
  COM2: "",
  PRECISION_JURIDIQUE: "",
  CONTACT: "mediatheque.patrimoine@culture.gouv.fr",
  COOR: "",
  COORM: "",
  COPY: "© Monuments historiques",
  DATE: ["1981"],
  DBOR: [],
  DENO: ["bateau"],
  DENQ: [],
  DEPL: "",
  DESC: "Doris à moteur.",
  DIMS: "",
  DMAJ: "2019-06-10",
  DMIS: "2017-05-26",
  DOMN: "",
  DOSADRS: "",
  DOSS: ["dossier individuel"],
  DOSURL: "",
  DOSURLPDF: "",
  DPRO: "2016/08/16 : classé au titre objet",
  DPT: "975",
  EDIF: "",
  EDIF2: "",
  EMPL: "Dans l'atelier du Père Pierre.",
  EMPL2: "",
  ETAT: ["oeuvre restaurée", "en état de naviguer"],
  ETUD: "liste objets classés MH",
  EXEC: "",
  EXPO: "",
  HIST: "Depuis 25 ans, l'association des Zigotos",
  IDAGR: [],
  IMAGE: "",
  IMG: [],
  IMPL: "",
  INSC: [],
  INSEE: "97502",
  INSEE2: "",
  INTE: "",
  JDAT: [],
  LBASE2: "",
  LIENS: [],
  LIEU: "",
  LMDP: "",
  LOCA: "",
  MATR: [],
  MFICH: [],
  MICR: "",
  MOSA: "",
  NART: "",
  NINV: "",
  NOMS: [],
  NUMA: "",
  NUMP: "",
  OBS: "",
  ORIG: "",
  PAPP: "",
  PARN: [],
  PART: [],
  PDEN: ["doris"],
  PDIM: "",
  PERS: [],
  PETA: "Oeuvre restaurée en 2015-2016 par l'Atelier du Père Pierre.",
  PHOTO: "",
  PINS: "",
  PINT: "",
  PLOC: "",
  PPRO: "Arrêté de classement n° 056. CNMH 01/02/2016. Propriété de l'association les Zigotos.",
  PREP: "",
  PROT: "classé au titre objet",
  REFA: [],
  REFE: [],
  REFM: "",
  REFP: [],
  REG: "Saint-Pierre-et-Miquelon",
  RENP: [],
  RENV: [],
  REPR: [],
  SCLD: [],
  SCLE: ["4e quart 20e siècle"],
  SCLX: ["20e s."],
  SOUR: "",
  STAD: [],
  STAT: ["propriété d'une association"],
  STRU: [],
  THEM: "",
  TICO: "doris Saint-Etienne",
  TITR: "Saint-Etienne",
  TOUT: "",
  VIDEO: [],
  VOLS: "",
  WADRS: "",
  WCOM: "Saint-Pierre",
  WEB: "",
  WRENV: "",
  ZONE: "",
  DOSURLP: "",
  REF: "PM97500018",
  MEMOIRE: []
};
