module.exports = {
  PRODUCTEUR: "État",
  CONTIENT_IMAGE: "non",
  ACQU: "1988 : objet de collection accepté en dation (Dation Verne, cote : MJV 83-12 à 83-16)",
  ADRS: "Héronnière (rue de l') 15",
  ADRS2: "",
  AFIG: [],
  AIRE: "",
  APPL: "Dation Verne",
  ATEL: "",
  AUTP: "",
  AUTR: ["Verne Jules (écrivain)"],
  BIBL: "",
  CANT: "",
  CATE: [],
  COM: "Nantes",
  COM2: "",
  CONTACT: "mediatheque.patrimoine@culture.gouv.fr",
  COOR: "",
  COORM: "",
  COPY: "(c) Centre des monuments nationaux",
  DATE: [],
  DBOR: [],
  DENO: ["manuscrit (3)"],
  DENQ: ["2008"],
  DEPL: "",
  DESC: "Ensemble de trois manuscrits.£De la Terre à la Lune : 138 feuillets paginés 1-275 dans une boîte.£Autour de la Lune : 1ère version de 41 feuillets dans une boîte et mise au net autographe de 130 feuillets paginés 1, 1 bis, 1ter-251 et 1-6 dans une boîte.£L'île mystérieuse : 1ère version incomplète comprenant la deuxième partie : chapitres 1-20 et la troisième partie : chapitres 1-6 et 13-18 (incomplets) en 142 feuillets dans une boîte où les pages 89-90 manquent et mise au net complète en partie autographe en 252 feuillets dans une boîte.",
  DIMS: "De la Terre à la Lune : h = 27,3 ; la = 21£Autour de la Lune : h = 32 ; la = 206, mise au net : h = 27,3 ; la = 21,1 ; h = 24,6 ; la = 18,6 ; h = 21,5 ; la = 15,5£L'Ile mystérieuse : h = 21,3 ; la = 21 et h = 31,1 ; la = 20,4, mise au net : h = 31,1 ; la = 21,4",
  DMAJ: "2019-11-13",
  DMIS: "2008-12-08",
  DOMN: "",
  DOSADRS: "",
  DOSS: ["dossier individuel"],
  DOSURL: "",
  DOSURLP: "",
  DPRO: "",
  DPT: "44",
  EDIF: "Bibliothèque municipale",
  EDIF2: "",
  EMPL: "",
  EMPL2: "",
ETAT: ["mauvais état"],
  ETUD: "recensement des oeuvres appartenant à l'Etat",
  EXEC: "",
  EXPO: "",
  HIST: "La dation complète le fonds Jules Verne mis en valeur au sein du Centre d'études verniennes et du Musée Jules Verne de la Bibliothèque municipale de Nantes. Les manuscrits de 99 romans, nouvelles, pièces de théâtre et autres écrits y sont conservés, corpus unique permettant de suivre l'élaboration de l'oeuvre. C'est la quasi-totalité des oeuvres, publiées ou non du vivant de leur auteur qui est ainsi réunie sous forme d'avant-textes même si manquent quelques titres majeurs : Vingt mille lieues sous les mers, Cinq semaines en ballon, Voyage au centre de la terre, les Cinq cents millions de la Bégum, le Docteur Ox et Edom.",
  IDAGR: [],
  IMAGE: "",
  IMG: [],
  IMPL: "",
  INSC: [],
  INSEE: "44109",
  INSEE2: "",
  INTE: "",
  JDAT: [],
  LBASE2: "",
  LIENS: [],
  LIEU: "",
  LMDP: "",
  LOCA: "",
  MATR: ["papier"],
  MFICH: [],
  MICR: "",
  MOSA: "",
  NART: "",
  NINV: "",
  NOMS: ["Valérie Langbour"],
  NUMA: "",
  NUMP: "",
  OBS: "",
  ORIG: "dépôt de l'Etat",
  PAPP: "",
  PARN: [],
  PART: [],
  PDEN: ["collection"],
  PDIM: "",
  PERS: ["Verne (offreur de la dation)"],
  PETA: "Manuscrit autographe 'Autour de la Lune' très abimé, traces de moisissures au bas des feuillets.",
  PHOTO: "",
  PINS: "",
  PINT: "",
  PLOC: "",
  PPRO: "",
  PREP: "",
  PROT: "",
REFA: [],
  REFE: [],
  REFM: "",
  REFP: [],
  REG: "Pays de la Loire",
  RENP: [],
  RENV: [],
  REPR: [],
  SCLD: [],
  SCLE: ["19e siècle"],
  SCLX: ["19e s."],
  SOUR: "",
  STAD: [],
  STAT: ["propriété de l'Etat"],
  STRU: [],
  THEM: "",
  TICO: "Dation Verne (Nantes, 1988) comprenant 3 manuscrits de Jules Verne",
  TITR: "",
  TOUT: "   ",
  VIDEO: ["mem/dation/B441096101_MJV_83_15_001.jpg", "mem/dation/B441096101_MJV_83_15_001-v.jpg", "mem/dation/B441096101_MJV_83_12_002.jpg", "mem/dation/B441096101_MJV_83_12_002-v.jpg", "mem/dation/B441096101_MJV_83_13_002.jpg", "mem/dation/B441096101_MJV_83_13_002-v.jpg"],
  VOLS: "",
  WADRS: "15 rue de l'Héronnière",
  WCOM: "Nantes",
  WEB: "",
  WRENV: "",
  ZONE: "",
  REF: "EM000000010",
  MEMOIRE: [],
  BASE: "Patrimoine mobilier (Palissy)",
  DOSURLPDF: "",
  POP_CONTIENT_GEOLOCALISATION: "non",
  POP_COORDONNEES: {
      lat: 0,
      lon: 0
  },
  POP_COMMENTAIRES: ["Le champ CONTACT ne doit pas être vide"],
  POP_FLAGS: ["DOSS_EMPTY", "ETUD_EMPTY", "COPY_EMPTY", "TICO_EMPTY", "CONTACT_EMPTY"],
  DPT_LETTRE: "Loire-Atlantique",
  MANQUANT: [],
  POP_ARRETE_PROTECTION: [],
  POP_DOSSIER_PROTECTION: [],
  POP_DOSSIER_VERT: "",
  POP_IMPORT: [],
  PRECISION_JURIDIQUE: "",
  POP_COORDINATES_POLYGON: {
      type: "Polygon",
      coordinates: []
  },
  REFJOC: [],
  REFMUS: []
};
